export const allProdactCards = localStorage.getItem("prod")
  ? JSON.parse(localStorage.getItem("prod"))
  : [
      {
        id: 1,
        title: "Kungaboqar yog'i Oila tanlovi,tozalangan va xidsizlantirilgan",
        heart: "⭐",
        content: "3.6 (125 sharhlar)",
        rasrochka: "1716 so'm/oyiga",
        realPrice: "25 000",
        discount: "16 900 so'm",
        img: "./img/kungaboqar.svg",
        isLiked: false,
      },
      {
        id: 2,
        title: "Smartfon Xiaomi Redmi Note 13,6/128 GB, 8/128 GB, 8/256GB,",
        content: "4.7 (4236 sharhlar)",
        heart: "⭐",
        rasrochka: "218 000 so'm/oyiga",
        realPrice: "2 500 000",
        discount: "1 850 000 so'm",
        img: "img/phone.svg",
        isLiked: false,
      },
      {
        id: 3,
        title: "Televizor Samsung Crystal UHD 4K43, 50, 55, 65 CU7100 Smart TV",
        content: "4.2 (15 sharhlar)",
        heart: "⭐",
        rasrochka: "132 000 so'm/oyiga",
        realPrice: "1 500 000",
        discount: "1 199 000 so'm",
        img: "img/tv.svg",
        isLiked: false,
      },
      {
        id: 4,
        title:
          "Yostiqlar to'plami, bambukdan,gipoallergenli, ekologik toza, 70 ",
        content: "3.8 (853 sharhlar)",
        heart: "⭐",
        rasrochka: "8000 so'm/oyiga",
        realPrice: "50 000",
        discount: "38 000 so'm",
        img: "img/yostiqlar.svg",
        isLiked: false,
      },
      {
        id: 5,
        title:
          "Sport kostyumi o'g'il bolalar uchun DUDUKA TRENDS. To'plam Hudi…",
        content: "4 (1268 sharhlar)",
        heart: "⭐",
        rasrochka: "19 000 so'm/oyiga",
        realPrice: "240 000",
        discount: "149 900 so'm",
        img: "img/sport_kiyim.svg",
        isLiked: false,
      },
    ];
